### ISSUE TITLE
The linux nightlies have been failing since the 25th

### ISSUE THREAD

**Issue by Stebalien** [rust-lang/rust-buildbot#107]
It appears that there's some issue building LLVM:

Latest failure: http://buildbot.rust-lang.org/builders/nightly-dist-rustc-linux/builds/570/steps/compile/logs/stdio
Linux nightly: http://buildbot.rust-lang.org/builders/nightly-dist-rustc-linux

**Comment by alexcrichton** [comment]
Indeed! https://github.com/rust-lang/rust/pull/34519 was the first attempt at a fix and https://github.com/rust-lang/rust/pull/34553 is the follow-up now that they're still failing. I'm gonna close this for now but we're certainly aware of the problem!

**Comment by Stebalien** [comment]
Sorry. I assumed this was a build-bot issue.
