### ISSUE TITLE
stunnel on OSX is crazy slow

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/rust-buildbot#111]
The packaging builders on nightly have an "upload" step where they upload their artifacts to the buildmaster, but on the macs this can take _hours_ where the Linux/Windows machine take seconds. The buildmaster is on EC2 and so are the Linux/Windows machines, but we're pushing at most 1GB of data from Macstadium to EC2 which shouldn't take an hour.

I've watched locally and it looks like stunnel is uploading at ~100KB/s. So far I've tried (none have worked)
- Restarting stunnel
- Adding TCP_NODELAY to our stunnel config on the client
- Updating stunnel to 5.35

I also was able to shove about 10MB/s of zeros via `nc` to the buildmaster, so I don't think the network is at fault here.

cc @brson this is probably causing the invalidation script to get fired _before_ we actually upload artifacts
cc @edunham, @larsbergstrom -- infra issue, y'all seen this over at servo?

**Comment by alexcrichton** [comment]
Well actually now that I think about it I have no proof that it's stunnel. It could be buildbot

**Comment by larsbergstrom** [comment]
Have you tried to VNC or ssh into the mac builders & just scp files over? We haven't seen any network bandwidth problems, but we do all of our publishing of builds directly from the builders to s3 buckets, and it's only a few hundreds of megs.

If it's slow when doing an scp, I'd definitely open up a support ticket to have them take al ook at the machine. Particularly with the Mac Minis, we've definitely seen... variable... performance from machine to machine. I think we have twice asked them to just dump a machine and give us a new one to start over with when we were totally unable to figure out why a particular Mini was having slow disk or flaky network connections even after a full OS reinstall.

**Comment by alexcrichton** [comment]
I tested the network connection manually (had to get through some firewalls first) and had 10MB/s between the two machines, so I don't think it was the network unfortunately :(

**Comment by edunham** [comment]
Rust is not presently running its own osx infra
