### ISSUE TITLE
Dist builder appears to no longer be using centos

### ISSUE THREAD

**Issue by aidanhs** [rust-lang/rust-buildbot#116]
https://buildbot.rust-lang.org/builders/nightly-dist-rustc-musl-linux/builds/322/steps/configure/logs/stdio (from https://buildbot.rust-lang.org/builders/nightly-dist-rustc-musl-linux/builds/322) has things like

```
configure: CFG_GCC              := /usr/bin/gcc (5.4.0-6ubuntu1)
```

which indicate that perhaps the dist builder is no longer centos. In fact, the dist centos should be version 4.7.4 - https://github.com/rust-lang/rust-buildbot/blob/master/slaves/dist/build_gcc.sh

Is https://github.com/rust-lang/rust-buildbot/blob/master/slaves/dist/Dockerfile (https://hub.docker.com/r/alexcrichton/rust-slave-dist/) no longer in use?

**Comment by alexcrichton** [comment]
Note that the musl build never used centos, we only use that for the Linux
nightlies

**Comment by aidanhs** [comment]
I see, the linux nightlies are built with centos for maximum glibc compatibility for the binaries (rustc and cargo). The musl stdlib doesn't need glibc compatibility, so is built in Ubuntu.

My problem is that I've been doing a full `./configure --target=x86_64-unknown-linux-musl [...] && make` rust build inside the centos container, which no longer works. I'll take this opportunity to look into how to just build the musl stdlib rather than getting you to bump binutils.

Thanks for the hint.
