### ISSUE TITLE
Nightly Linux 64bit failing

### ISSUE THREAD

**Issue by Stebalien** [rust-lang/rust-buildbot#12]
curl-sys isn't compiling because it can't find the OpenSSL libraries:
```rust
configure: error: OpenSSL libs and/or directories were not found where specified!
thread '<main>' panicked at 'assertion failed: t!(cmd . status (  )).success()', /home/rustbuild/src/rust-buildbot/slave/cargo-linux-64/.cargo/registry/src/github.com-1ecc6299db9ec823/curl-sys-0.1.21/build.rs:128
```
Full output: http://buildbot.rust-lang.org/builders/nightly-dist-cargo-linux-64/builds/135/steps/compile/logs/stdio

It's been failing since May 5th. I apologize if this isn't the right place to report this issue.

/cc @brson?

**Comment by alexcrichton** [comment]
Oh oops! I fixed this but forgot to restart buildbot. I have just done so and this should be moving forward now.

**Comment by Stebalien** [comment]
Thanks!
