### ISSUE TITLE
Enable LLVM assertions on more buildbots

### ISSUE THREAD

**Issue by retep998** [rust-lang/rust-buildbot#120]
A regression recently popped up which apparently would have been caught if the buildbots actually had LLVM assertions enabled https://github.com/rust-lang/rust/issues/35991#issuecomment-242515627

**Comment by TimNN** [comment]
cc rust-lang/rust#35998.

**Comment by alexcrichton** [comment]
@brson we already enable debug assertions on all bots, do you have any objections to just always enabling llvm assertions on all bots?

**Comment by brson** [comment]
@alexcrichton llvm assertions have a significant compile-time performance penalty. I don't personally mind taking that hit but it will slow down landing velocity.

**Comment by brson** [comment]
Also, not on the dist bots please.
