### ISSUE TITLE
Build for ARM Musl targets

### ISSUE THREAD

**Issue by lilianmoraru** [rust-lang/rust-buildbot#128]
[Rust now supports](https://github.com/rust-lang/rust/pull/35060) these additional targets:
```
arm-unknown-linux-musleabi
arm-unknown-linux-musleabihf
armv7-unknown-linux-musleabihf
```

Could we get builds for these targets?

**Comment by lilianmoraru** [comment]
ping @alexcrichton

**Comment by alexcrichton** [comment]
cc @japaric as well

Unfortunately it's pretty difficult to add these today. Even if we had an image with all the relevant `libc.a` files in it we'd have to have a way of pointing the build system at all of them simultaneously. The `./configure` script only supports at most one musl target, and while rustbuild supports more than one at a time it isn't easily configurable from buildbot.

Will basically take some refactoring to get this to work.

**Comment by alexcrichton** [comment]
Targets are added and deployed!

**Comment by alexcrichton** [comment]
Nightlies should hopefully come tomorrow night, but I'll debug failures if they happen.

**Comment by lilianmoraru** [comment]
Thank you!

**Comment by alexcrichton** [comment]
Complications last night prevented these nightlies from going out, hopefully tonight though!

**Comment by lilianmoraru** [comment]
@alexcrichton `rustup` still says `'arm-unknown-linux-musleabi' is unavailable for download`
Where could I check the status for these?

**Comment by japaric** [comment]
> I see this one passed

**All** the "nightly-dist-*" jobs [here](https://buildbot.rust-lang.org/waterfall?refresh=15) must pass (become green) but looks like one of the last steps, [nightly-dist-packaging-linux](https://buildbot.rust-lang.org/builders/nightly-dist-packaging-linux/builds/554), failed today.

**Comment by alexcrichton** [comment]
Another hiccup last night, but a new nightly and these targets are now out.

**Comment by lilianmoraru** [comment]
Yey, it works now.
Thanks!!
