### ISSUE TITLE
Find command errors in `SetPropertyFromCommand` for property "freshconfig" on builder `auto-win-msvc-64-opt-rustbuild`

### ISSUE THREAD

**Issue by DirkyJerky** [rust-lang/rust-buildbot#140]
On an unrelated build: https://buildbot.rust-lang.org/builders/auto-win-msvc-64-opt-rustbuild/builds/3217
The """freshconfig""" key is set to the value """0 /usr/bin/find: paths must precede expression: ^ Usage: /usr/bin/find [-H] [-L] [-P] [-Olevel] [-D help|tree|search|stat|rates|opt|exec] [path...] [expression]"""

Relevant source: https://github.com/rust-lang/rust-buildbot/blob/master/master/master.cfg#LC976

The find command is valid on my macOS machine here.

It caused the `should_wipe` function to return the wrong value, making the `WORK_DIR` directory to not be removed before `git clean -d -f -f` in the next step. No clue if it contributed to the build failure.

**Comment by alexcrichton** [comment]
auto bots are on there way out, so closing.
