### ISSUE TITLE
stable dist choked on artifact consolidation

### ISSUE THREAD

**Issue by xen0n** [rust-lang/rust-buildbot#154]
[Example](https://buildbot.rust-lang.org/builders/stable-dist-rustc-cross-rustbuild-linux/builds/10/steps/consolidate%20artifacts/logs/stdio).

Reason is multiple files with the same name inside the different source directories; we need to filter them somehow. Particularly the `rust-src` tarballs and maybe docs? A `ls -R` should be helpful.

**Comment by brson** [comment]
The problem here I think is that rustbuild is not cleaning up the dist directory before running dist.

The collisions are with __1.15.0__ on a build of __1.15.1__. These are stale binaries just sitting on the mac builders. Only happens with macs because other platforms run in clean containers.

**Comment by brson** [comment]
Nightly and beta produce artifacts that are not differentiated by the name, which is why we didn't see it until a stable release.

**Comment by xen0n** [comment]
Hmm, the explanation makes sense! Manually cleaning the dist dirs of the mac builders and re-triggering a packaging step somehow should fix packaging then.

**Comment by brson** [comment]
Fixed on master by https://github.com/rust-lang/rust/pull/39622. Fixed on stable by logging into the build slaves and cleaning manually.
