### ISSUE TITLE
Does this repo need a LICENSE file?

### ISSUE THREAD

**Issue by edunham** [rust-lang/rust-buildbot#19]
We're publishing it publicly on Github, which implies an intent to share it with the world, but we don't tell people what they're actually allowed to do with it. Since it's all configuration files, I don't know whether CC-BY or the standard Rust code license would be more appropriate. 

We should either add a LICENSE/COPYING file or a note in the README discussing how people are allowed to use the contents of this repo.

**Comment by alexcrichton** [comment]
One now exists
