### ISSUE TITLE
Consider moving from master/slave terminology

### ISSUE THREAD

**Issue by cllns** [rust-lang/rust-buildbot#2]
This seems like an internal tool, but it might be a good idea to change from 'master/slave' to something less problematic. 

I'm not familiar with this tool, but `primary`/`replica` might work. (or leader/follower)

@steveklabnik @brson, thoughts?

**Comment by bheesham** [comment]
Yeah, that would be tricky. You can always fork Buildbot and hope a simple text replacement would work

Unless writing an alternative from the scratch up to be slightly easier to modify so that BORS integration isn't a massive pain. But who'd do that, right? Right? **Weak laughter.**

**Comment by tbu-** [comment]
@steveklabnik Primary/replica doesn't seem to fit, as there's a controller (the current "master") which completely controls the other instances (the current "slaves"), i.e. they're not replicas of the primary.

**Comment by cllns** [comment]
@tbu- What about leader/follower?

**Comment by tbu-** [comment]
That sounds better.

**Comment by trevrosen** [comment]
I think "leader/follower" works as a pretty much universal replacement for "master/slave". I don't do any Rust at work, but we've started to use this nomenclature for multi-server environments there.

**Comment by eevee** [comment]
uwsgi uses emperor/vassal for some similar feature.

"peon" is a great word too.  but then i'm inclined towards colorful names  :)

**Comment by tonylukasavage** [comment]
leader/follower is pretty popular among projects making this particular change.

**Comment by samphippen** [comment]
@steveklabnik leader/follower seems correct in this case for me.

**Comment by coderanger** [comment]
For CI stuff in the past I've used "server/worker" or "server/builder".

**Comment by jedahan** [comment]
leader/follower seems the more general than leader/builder

though I like both

**Comment by joneslee85** [comment]
Oh my, please check https://github.com/django/django/pull/2692

**Comment by alex** [comment]
coordinator/worker is probably what I'd use if I were building a CI system.

**Comment by effigies** [comment]
Would suggest controller/worker, but +1 to coordinator/worker, too.

**Comment by timplunkett** [comment]
Drupal decided on using `primary`/`replica`, following Django's lead.

**Comment by alex** [comment]
A build system's naming scheme isn't describing the same thing as a
database system; I do think primary/replica is the right naming for
database replication schemes.

On Wed, Feb 4, 2015 at 3:25 PM, Tim Plunkett <notifications@github.com>
wrote:

> Drupal decided on using primary/replica, following Django's lead.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rust-lang/rust-buildbot/issues/2#issuecomment-72962526>
> .
>



-- 
"I disapprove of what you say, but I will defend to the death your right to
say it." -- Evelyn Beatrice Hall (summarizing Voltaire)
"The people's good is the highest law." -- Cicero
GPG Key fingerprint: 125F 5C67 DFE9 4084

**Comment by tomburns** [comment]
+1 for leader / follower, given the context.

**Comment by zjjw** [comment]
`primary/secondary` also works, if `primary/replica` seems weird.

**Comment by reaperhulk** [comment]
http://trac.buildbot.net/ticket/2340 may also be of interest.

**Comment by mikeedwards** [comment]
primary/secondary? That's sort of what mongo does:
http://docs.mongodb.org/manual/core/replication/

Primary and replica would work, too, but that might be too specific in terms of function of the "non-primary" machine. Secondary is nicely general, if that matters.

**Comment by tbu-** [comment]
@zjjw Your terminology doesn't quite fit, it might fit for databases, but not for build servers.

server/worker might fit.

**Comment by cllns** [comment]
@reaperhulk I was in the process of writing a comment there when you posted the link :+1:

**Comment by tomjakubowski** [comment]
We should avoid using "leader" in upper case or any other context where it could be construed as a title.

**Comment by kamalmarhubi** [comment]
slave -> worker above the rest of the suggestions.

Perhaps master is all right with that change, trying to decide for myself.

For the master:
- leave it as master. Trying to decide for myself if that's all right with slave -> worker
- coordinator: I think this works well
- server: I don't know buildbot architecture, but if the 'master' is the process that receives requests and sends them out, 'server' would be all right. If it polls the repo and only manages the workers, then I don't think it fits.
- leader: leader / follower to me suggest a distributed database or a paxos or raft like replicated state machine.
- primary: primary / secondary suggest the two components are of the same class, which is not the case.

**Comment by colingourlay** [comment]
I'm throwing in `gru` / `minion`.

**Comment by O-I** [comment]
I think `primary/replica` has precedent in replacing `master/slave` terminology like in the aforementioned Django issue mentioned by @joneslee85, but I find myself more in the `leader/follower` camp.

If it didn't make things even more confusing, I'd suggest something like `yang/yin`. :smiley:

**Comment by locks** [comment]
CouchDB also switched to primary / replica, if I remember correctly: https://issues.apache.org/jira/browse/COUCHDB-2248

**Comment by crazymykl** [comment]
Although `leader`/`follower` looks to be in the lead, I humbly propose `exemplar`/`aspirant`.

**Comment by Manishearth** [comment]
`primary/replica` sounds too database-y, and replication isn't exactly what's happening here.

I prefer `leader/follower`

**Comment by lukemayes** [comment]
@tbi- describing the current "master" as a controller made me think controller/drone or controller/worker might be good.

**Comment by tomjakubowski** [comment]
"Drone" is equally problematic in parts of the world ravaged by US military intervention.

**Comment by steveklabnik** [comment]
Thank you everyone for your suggestions.

Given that we're not a database, I agree that `primary`/`replica` doesn't make a lot of sense. But regardless, this really needs to be fixed upstream. Therefore, I'm doing two things:

1. Closing this in favor of http://trac.buildbot.net/ticket/2340
2. Working with said upstream to land a patch. I have been emailing with one of the committers about it, and they're favorable to the change, the work just needs done. I plan on implementing `leader`/`follower`.

If upstream ends up rejecting this, we can re-open and see what we can do, but for now, dealing with them is the correct course of action.

**Comment by dhuseby** [comment]
How about "gun" and "shovel"?

"You see in this world there's two kinds of people, my friend. Those with loaded guns, and those who dig. You dig."
https://www.youtube.com/watch?v=6YnryHbJqC4&t=3m34s

**Comment by willricketts** [comment]
I know... how about not being a pussy and calling it "master/slave?"

Jesus christ.
