### ISSUE TITLE
Better support of Tiers-2 platforms

### ISSUE THREAD

**Issue by semarie** [rust-lang/rust-buildbot#28]
Currently, Tiers-2 platforms (bitrig-64-opt, linux-musl-64-opt, freebsd10_32-1, freebsd10_64-1, dragonflybsd-64-opt, and openbsd-64-opt) have buildbot configuration but are ignored for any failure by @bors.

I wonder if it could be revised to be ignored only for failing in `test`, and make a failure on `compile` be blocking too for merging ?

Eventually having 3 levels for platforms:
 - Tiers-1 platforms: any failure is blocking
 - Tiers-2 platforms: any failure on compile is blocking (but failure on test are not)
 - Tiers-3 platforms: not blocking

I don't known enough buildbot for proposing PR. But I can try if this proposition have any interest.

**Comment by semarie** [comment]
Looking a builbot interface, all Tier-2 platforms seems to build reliabily.

The usecase is for `openbsd-64-opt`, that just break, because of merging of https://github.com/rust-lang/rust/pull/28543 (correction pending at https://github.com/rust-lang/rust/pull/28598).

**Comment by alexcrichton** [comment]
I think that we've basically done this now to the extent that we can. We're unfortunately not comfortable at this time gating on community-provided slaves at it means that we can't easily fix bugs or diagnose problems. What we can do, however, is cross compile the compiler from Linux to these platforms! 

We're now producing FreeBSD and NetBSD nightlies for the compiler and it should be easy enough to add more so long as we can create a cross compiler from each Linux to the target system.

In that sense, we've now raised the bar from "well we hope community slaves will solve this one day" to "well so long as you can cross-compile from linux we can guarantee it keeps compiling"
