### ISSUE TITLE
Non-privileged users can't cancel non-dist builds

### ISSUE THREAD

**Issue by brson** [rust-lang/rust-buildbot#5]
We [recently](https://github.com/rust-lang/rust-buildbot/pull/4) added a privileged user for building 'dist' builds. After that patch though non-privileged users can no longer cancel non-dist builds.

cc @bheesham @alexcrichton

**Comment by bheesham** [comment]
Ah, I think I know what's up here.

On line [1619 of master.cfg](https://github.com/rust-lang/rust-buildbot/blob/master/master/master.cfg#L1696), `stopBuild` provides a `BuildStatus` object and not a `BuilderStatus`, which is what the `userAuth` callback expects. So it's probably running into an AttributeError?

Calling the `getBuilder()` function on the object should give us what we're looking for.

**Comment by alexcrichton** [comment]
non-dist builds are no longer a thing, so closing.
