### ISSUE TITLE
new binary releases for mips and arm

### ISSUE THREAD

**Issue by japaric** [rust-lang/rust-buildbot#78]
Just a reminder of the extra binaries that can be build in the linux-cross image after its next rebuild.

- [x] libstd for mips(el)-unknown-linux-musl (2 targets)
    - Image: linux-cross
    - Uses: the old build system
    - Probably just tack thxs on top of the 'nightly-dist-rustc-cross-linux' builder. Add both targets
        to the `--target` argument of the `configure` script.
- [x] rustc for arm(v7)-unknown-linux-gnueabi(hf) (3 hosts)
    - Image: linux-cross
    - Uses: rustbuild
    - ~~Blocked on: rust-lang/rust#32237~~
    - This wants a new builder.
    - Since this job will also produce libstd tarballs, perhaps we can remove these 3 targets from the 'nightly-dist-rustc-cross-linux' builder and have this builder upload 3 rustc tarballs and 3 libstd tarballs.
- [ ] libstd for i686-unknown-linux-musl
    - Image: linux
    - Uses: the old build system
    - ~~Blocked on #79~~
    - This should go in its own builder because AFAICT one can't build libstd for two static musl targets. And we can't do that because we would need to pass one `--musl-root` to configure for each target but that flag only accepts one argument.

cc @alexcrichton

**Comment by japaric** [comment]
Added libstd for i686-musl to the top comment.

**Comment by alexcrichton** [comment]
Working on adding netbsd/freebsd compilers as well, hope to have this by the end of the week.

**Comment by alexcrichton** [comment]
Lotsa buildbot changes here as well to take care of

**Comment by alexcrichton** [comment]
Extracting out the last bit to https://github.com/rust-lang/rust-buildbot/issues/88
