### ISSUE TITLE
Add (temporary) MIR builders.

### ISSUE THREAD

**Issue by eddyb** [rust-lang/rust-buildbot#82]
Until MIR is turned on by default for everyone, we want to make sure we don't regress.

In rust-lang/rust#32080 I've tagged relevant functions in tests that involve features not yet in MIR (such as debuginfo or overflow checks) with `#[rustc_no_mir]`, and we can keep adding those *as long as we track them*, so I believe the new MIR builders should gate all builds.

We're going to need at least one UNIX builder and one MSVC because of the unwinding complexities found in the latter (I don't even know if MSVC can bootstrap w/ MIR right now).

Blocked on the snapshots being added in rust-lang/rust#32345. cc @alexcrichton

**Comment by alexcrichton** [comment]
This is just enabled with `./configure --enable-orbit`, right?

**Comment by alexcrichton** [comment]
And then we just run `make check`?

**Comment by eddyb** [comment]
@alexcrichton Correct, I did this on a 64-bit linux machine and it completed successfully.

**Comment by alexcrichton** [comment]
Ok, done in https://github.com/rust-lang/rust-buildbot/commit/4d3bc18bec466a2e6c91b5a72b36f1540fc482da, will deploy shortly
