### ISSUE TITLE
Add aarch64-unknown-linux-gnu compiler

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/rust-buildbot#85]
* [x] Pull the glibc version in the cross image backwards, probably the same way as arm-unknown-linux-gnueabi
* [x] Add auto builder cross-compiling to aarch64 (https://github.com/rust-lang/rust-buildbot/commit/346e9a28032410a741c8fc92dc2da5fc96e338a4)
* [x] Add nightly builder cross compiling to aarch64 for the compiler (https://github.com/rust-lang/rust-buildbot/commit/346e9a28032410a741c8fc92dc2da5fc96e338a4)
* [x] Add cargo build for aarch64 (https://github.com/rust-lang/cargo/pull/2538)
* [x] Add rustup build for aarch64 (https://github.com/rust-lang-nursery/multirust-rs/pull/257)

cc @japaric  
cc @brandonedens

**Comment by japaric** [comment]
> Pull the glibc version in the cross image backwards, probably the same way as arm-unknown-linux-gnueabi

Support for aarch64 was introduced in [glibc-2.17](https://sourceware.org/ml/libc-announce/2012/msg00001.html), so I guess that's what we should use. I'll look into the crostool-ng config.

**Comment by alexcrichton** [comment]
Awesome, thanks @japaric!

**Comment by alexcrichton** [comment]
Done! I'll deploy shortly.
