### ISSUE TITLE
Add i686-unknown-linux-musl cross-std builder

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/rust-buildbot#88]
This should probably use the `linux` builder with the old build system as we would want to run a full `make check` like we do with the x86_64-bit musl support.

cc https://github.com/rust-lang/rust-buildbot/issues/78
cc @japaric

**Comment by alexcrichton** [comment]
Ok, this has a similar problem as the i586-unknown-linux-gnu builder. We can either (a) build and test this target like x86_64-unknown-linux-musl, or (b) only build it like we do for other cross targets. In either case we *cannot* build in the standard linux-cross image because there's no 32-bit linker/gcc there (the gcc-multilib package conflicts with all the cross-gcc packages).

So either we need to take the route of (a) which seems a bit heavyweight, or we need to figure out how to get a 32-bit compiler in the linux-cross image.

**Comment by japaric** [comment]
> take the route of (a) which seems a bit heavyweight

What makes you say that? Because building std for i686-musl would require running the full test suite?

> or we need to figure out how to get a 32-bit compiler in the linux-cross image.

We can use crosstool-ng to build a toolchain (+ libc/libgcc/etc) for i586 and another one for i686. Why two of them? Because we had problems with using a lower bound compiler for two slightly similar targets: arm-gnueabihf and armv7-gnueabihf. Let me know if you want to go down this route, and I'll look into the crosstool-ng configuration.

**Comment by alexcrichton** [comment]
Yeah it's true we could just not run tests, from a convenience point of view it'd be easier to run in the normal `linux-cross` image as that's where all other cross compilations happen. Otherwise we'd need to set up a new builder and configure it correctly.

That seems albeit easier than setting up a whole new gcc toolchain for two targets though, so that's perhaps just the best option. Setting up a dedicated builder to cross to 32-bit and maybe smoke test musl at least.

**Comment by alexcrichton** [comment]
Working on this over at https://github.com/alexcrichton/rust-buildbot/tree/more-cross-builders

**Comment by alexcrichton** [comment]
Ok, I've made a PR: https://github.com/rust-lang/rust-buildbot/pull/95

We'll need to add Cargo + rustup builds for i686-unknown-freebsd as well eventually to push that compiler over the finish line.

**Comment by alexcrichton** [comment]
Done!
