### ISSUE TITLE
Add i686-linux-android builds

### ISSUE THREAD

**Issue by froydnj** [rust-lang/rust-buildbot#97]
As Firefox looks to adding Rust support on all of its supported platforms, we'd like `i686-linux-android` (tier 3) to be given the same status as `arm-linux-androideabi` (tier 2).  Part of that is having buildbot understand how to build binaries.

**Comment by alexcrichton** [comment]
I'll look into doing this once we get https://github.com/rust-lang/rust-buildbot/pull/99 in

**Comment by alexcrichton** [comment]
Fixed in https://github.com/rust-lang/rust-buildbot/commit/e5ac28a54973ea7c07f55048c2038354108ad730, when #99 merges with the NDK updates I'll deploy and this'll make its way out
